version: '3'

services:
  web:
    build: ./starstone_db_manager
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    build: ./starstone_db
    ports:
      - '3309:3306'
    volumes:
      - /var/lib/mysql
    